### ISSUE TITLE
Only the last 30 days?

### ISSUE THREAD

**Issue by djlongy** [MarkBaggett/srum-dump#23]
Does SRUM_dump2.exe only retrieve the last 30 days of records?
I have a SRUDB.dat where I can see much older artifacts of interest in ASCII/HEX view, but SRUM_dump2 doesn't seem to retrieve any info about this. The events of interest occurred 3 years before the last event in SRUDB.dat

**Comment by MarkBaggett** [comment]
I am dumping every record that is in the database.  If you hit control-alt-delete, open TASK MANAGER, then go to the "APP HISTORY" tab it will say something like "Resource usage since MM/DD/YYYY for current user"   That is the oldest piece of data in SRUDB.dat.   If you are seeing something that is older I am interested in understanding what it is to see if there is some way to retrieve it, but as far as I know we can only get 30 days worth of logs.
